use datadoctors;
DROP TABLE DOCTOR; # Drop tables with foreign keys first
DROP TABLE NURSES;
DROP TABLE STAFF;
DROP TABLE BILLING;
DROP TABLE APPOINTMENTS;

DROP TABLE HOSPITAL; 
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE PATIENT;
DROP TABLE PATIENTQUEUE;
DROP TABLE MEDICALHISTORY;
