USE datadoctors;
DROP TABLE BILLING;
DROP TABLE CURRENTPATIENT;
DROP TABLE PATIENTQUEUE;
DROP TABLE APPOINTMENTS;
DROP TABLE MEDICALHISTORY;

DROP TABLE PATIENT;
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE HOSPITAL; 
